In [1]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [4]:
import numpy as np
list1=[]
list2=[]

#taking values for list1
print("1st List")
for i in range(5):
    x= int(input())
    list1.append(x)

#taking values for list2

print("2nd List")
for i in range(5):
    y=int(input())
    list2.append(y)
    
#conversion list to array

arr1 = np.array(list1)
arr2 = np.array(list2)

#concatenation of aaray1 and array2

array_concat = np.concatenate((arr1,arr2))
print('Concatenation of arrays:',array_concat)

# sorting arrays

print("Sorted array1:",np.sort(arr1))
print("Sorted array2:",np.sort(arr2))
print("Sorted concatenated array:",np.sort(array_concat))

1st List
2
4
6
1
8
2nd List
12
22
34
65
55
Concatenation of arrays: [ 2  4  6  1  8 12 22 34 65 55]
Sorted array1: [1 2 4 6 8]
Sorted array2: [12 22 34 55 65]
Sorted concatenated array: [ 1  2  4  6  8 12 22 34 55 65]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [1]:
import numpy as np

#creating an array with random values
arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
print("Array =\n",arr)

print("Dimension of array:",arr.ndim,"D")
print("size of",arr.shape,"array:", arr.size)

Array =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of array: 2 D
size of (3, 3) array: 9


In [9]:
import numpy as np

#creating 1D array
arr=np.array([5,4,5])
print(arr)
print('Shape of 1D Array:',arr.shape)

#converting 1D Array to 2D Array

#row wise
arr_row = arr[np.newaxis, :]
print("Shape of 2d Array in row major :",arr_row.shape)

#column wise
arr_col = arr[:,np.newaxis]
print("Shape of 2D Array in column major :",arr_col.shape)


[5 4 5]
Shape of 1D Array: (3,)
Shape of 2d Array in row major : (1, 3)
Shape of 2D Array in column major : (3, 1)


In [10]:
import numpy as np

#creating two square numpy arrays
arr1 = np.square([2,4,6,8,10])
arr2 = np.square([1,3,5,7,9])

#Stacking arrays horizontally
print("Horizontally Stacked arrays :",np.hstack((arr1,arr2)))

#Stacking arrays vertically
print("Vertically Stacked arrays :",np.vstack((arr1,arr2)))

Horizontally Stacked arrays : [  4  16  36  64 100   1   9  25  49  81]
Vertically Stacked arrays : [[  4  16  36  64 100]
 [  1   9  25  49  81]]


In [11]:
import numpy as np
arr = np.array([1, 1, 2, 3, 4, 4, 1])

#getting unique items and its counts
unique, counts = np.unique(arr, return_counts=True)

array = np.asarray((unique, counts)).T
print(array)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
